package ExceptionDemo1;

public class ExceptionDemo02{
    public static void main(String[] args) {
        /*
        * 自己处理 捕获异常
        * try{
        *   可能出现异常的代码
        * }catch(异常类型 变量名){
        *   异常的处理代码
        * }
        *
        * */



        int[] a={1,2,3,4,5};
        System.out.println("程序继续执行");
        System.out.println(a[10]);




    }
}
